---
apiVersion: v1
kind: Namespace
metadata:
  name: dbt
  labels:
    name: dbt
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vertica_upsert
  namespace: dbt
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: project
              emptyDir: {}
            - name: profiles
              configMap:
                name: dbt-profiles
                items:
                  - key: profiles.yml
                    path: profiles.yml
          initContainers:
            - name: pull_project
              image: k8s.gcr.io/git-sync:v3.1.3
              volumeMounts:
                - name: project
                  mountPath: /usr/app
              env:
                - name: GIT_SYNC_REPO
                  value: "https://github.com/musaalp/design-patterns.git" ##repo-path-you-want-to-clone
                - name: GIT_SYNC_BRANCH
                  value: "master" ##repo-branch
                - name: GIT_SYNC_ROOT
                  value: /usr/app
                - name: GIT_SYNC_DEST
                  value: "vertica_upsert" ##path-where-you-want-to-clone
                - name: GIT_SYNC_PERIOD
                  value: "20"
                - name: GIT_SYNC_ONE_TIME
                  value: "false"
              securityContext:
                runAsUser: 0

          containers:
            - name: vertica_upsert
              image: dbt-vertica:latest
              imagePullPolicy: IfNotPresent
              command:
                - run-operation
                - run_proc
                - --project-dir
                - /usr/app/vertica_upsert
              volumeMounts:
                - name: project
                  mountPath: /usr/app
                - name: profiles
                  mountPath: /root/.dbt
