# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dbt
#   labels:
#     name: dbt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dbt
  name: dbt-vc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vertica-upsert
  namespace: dbt
spec:
  # securityContext:
  # fsGroup: 0
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: ssh-key
              secret:
                secretName: git-creds
                defaultMode: 0400
            - name: repo
              persistentVolumeClaim:
                claimName: dbt-vc
            - name: profiles
              configMap:
                name: dbt-profiles
                items:
                  - key: profiles.yml
                    path: profiles.yml
          initContainers:
            - name: gitsync
              image: k8s.gcr.io/git-sync:v3.1.3
              securityContext:
                runAsUser: 0 # git-sync user
                runAsNonRoot: false
              volumeMounts:
                - name: ssh-key
                  mountPath: "/etc/git-secret"
                  readOnly: true
                - name: repo
                  mountPath: /opt/repo
              env:
                - name: GIT_SYNC_REPO
                  value: "git@github.com:hieu2102/dbt-vertica-test-project.git" ##repo-path-you-want-to-clone
                - name: GIT_SYNC_BRANCH
                  value: "master" ##repo-branch
                - name: GIT_SYNC_ROOT
                  value: /opt/repo
                - name: GIT_SYNC_DEST
                  value: "vertica_upsert" ##path-where-you-want-to-clone
                - name: GIT_SYNC_PERIOD
                  value: "20"
                - name: GIT_SYNC_ONE_TIME
                  value: "true"
                - name: GIT_SYNC_VERBOSE
                  value: "9"
                - name: GIT_SYNC_SSH_KNOWN_HOSTS
                  value: "false"
              command:
                - /git-sync
                - --ssh
                - --ssh-known-hosts=false
          containers:
            - name: vertica-upsert
              image: dbt-vertica:latest
              imagePullPolicy: IfNotPresent
              command:
                - dbt
                - run-operation
                - run_proc
                - --project-dir
                - /usr/app/vertica_upsert
              volumeMounts:
                - name: repo
                  mountPath: /usr/app
                - name: profiles
                  mountPath: /root/.dbt
            - name: debug
              image: dbt-vertica:latest
              imagePullPolicy: IfNotPresent
              command:
                - ls
                - /usr/app/vertica_upsert
              volumeMounts:
                - name: repo
                  mountPath: /usr/app
                - name: profiles
                  mountPath: /root/.dbt
