apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: arcion
spec:
  containers:
    - image: alpine:3.12
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always
