---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: arcion
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: arcion
  name: arcion-config
  labels:
    app: arcion
data:
  DB_HOST: postgres-svc
  DB_PORT: "5432"
  DB_DATABASE: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  NTP_SERVER: ntp-server
